server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/auth/realms/demo

security:
  jwt:
    expected-audience: account

management:
  endpoint:
    web:
      exposure:
        include: health,info

kong:
  admin:
    base-url: http://host.docker.internal:3006/admin-api
    token: ""       # optional; remove if not used
    insecure-tls: false            # dev-only; use proper trust store in prod
    page-size: 1000
    timeout-ms: 5000

cache:
  kong:
    ttl-seconds: 15
